dist: focal
sudo: true

language: go
go:
  - "1.17.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
#    - CGO_ENABLED=0
    - GOLANGCI_LINTER_VERSION=v1.50.0 # github-releases:golangci/golangci-lint
    - COVERALLS_TOKEN=""
services:
  - docker

before_install:
  - go mod download
  - go install github.com/mattn/goveralls@v0.0.11 # github-releases:mattn/goveralls
  - docker pull lambci/lambda:go1.x
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_LINTER_VERSION

script:
  - golangci-lint run
  - go vet ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./mydemoskill ./cmd/mydemoskill
  - ./mydemoskill make --skill --models
  - ./test/test-lambda.sh

notifications:
  email:
    on_success: never
    on_failure: always
